"""CLI 退出码定义，对齐 PRD 8.5 错误码设计"""

EXIT_SUCCESS = 0
EXIT_INVALID_ARGS = 10
EXIT_TOKEN_INVALID = 20
EXIT_NOT_SUBSCRIBED = 21
EXIT_SUBSCRIPTION_EXPIRED = 22
EXIT_RATE_LIMITED = 30
EXIT_ACCESS_BLOCKED = 31
EXIT_NETWORK_ERROR = 40
EXIT_SERVER_ERROR = 41
EXIT_CHECKSUM_FAILED = 42
EXIT_PARTIAL_FAILURE = 43
EXIT_UNRECOVERABLE = 50
EXIT_USER_CANCELLED = 130
